#spring:
#  datasource:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/business_operation_guidance
#          username: root
#          password: 123456
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml
spring:
  datasource:
    dynamic:
      datasource:
        iam:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/business_operation_guidance
          username: root
          password: 123456
mysql:
  iam:
    liquibaseDataSource:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/o2o_oass?createDatabaseIfNotExist=true
      username: root
      password: 123456
      maxPoolSize: 2
      connectionTimeOut: 10000
      maxLifeTime: 600000

